{{- if .Values.ecrHelper.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "para.ecrHelperServiceAccountName" . }}
  labels:
    {{- include "para.labels" . | nindent 4 }}
  {{- with .Values.ecrHelper.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
