apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "para.fullname" . }}-data
  labels:
    {{- include "para.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.persistentVolumes.data.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumes.data.size }}
  {{- with .Values.persistentVolumes.data.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "para.fullname" . }}-lib
  labels:
    {{- include "para.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.persistentVolumes.lib.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumes.lib.size }}
  {{- with .Values.persistentVolumes.lib.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
