{{- $root := . }}
{{- with $root.Values.rootSecretOverride }}
{{- $secret := . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-root-secret" (include "para.fullname" $root)) $secret.name }}
  labels:
    {{- include "para.labels" $root | nindent 4 }}
    {{- with $secret.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: {{ default "Opaque" $secret.type }}
{{- with $secret.stringData }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
